# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-03 06:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LightningTalk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('speaker', models.CharField(max_length=255)),
                ('given_on', models.DateTimeField(verbose_name='date given')),
                ('embed_video_html', models.CharField(max_length=1023)),
            ],
        ),
    ]
