# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-03 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lightning_talks', '0002_auto_20160703_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lightningtalk',
            name='given_on',
            field=models.DateField(verbose_name='date given'),
        ),
    ]
